### ISSUE TITLE
No Simplifier.exe file

### ISSUE THREAD

**Issue by generic-placeholder-name** [mazeworks-security/Simplifier#8]
In the description, it is said that the project provides a `Simplifier.exe` executable file. However, it is not present in the GitHub repo.

**Comment by Colton1skees** [comment]
@generic-placeholder-name Did you build the repo using the steps under `Building`? The exact path will change depending on which .NET version and build configuration you are using - but it should be under `Simplifier\bin\BUILD_CONFIG\NET_VERSION\
Simplifier.exe`

**Comment by generic-placeholder-name** [comment]
Oh, I thought the .exe was provided in the repo. I'll build it.
